---

title: Prädikat
baseurl: "/praedikat-wertvoll"
url: "https://lodifice.github.io"

markdown: kramdown

sass:
  sass_dir: _scss
  style: :compressed

plugins:
  - jekyll

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

permalink: pretty
