---

title: Prädikat
baseurl: "/"
url: "https://prädik.at"

markdown: kramdown

sass:
  sass_dir: _scss
  style: :compressed

plugins:
  - jekyll

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

permalink: pretty
